const $=s=>document.querySelector(s);let render=()=>{},resetView=()=>{},playing=false,last=0;
const presets={tension:[100,0,0],shear:[0,0,60],biaxial:[100,20,35],compression:[-60,-60,0]};
function read(){return {xx:Number($('#xx').value)||0,yy:Number($('#yy').value)||0,xy:Number($('#xy').value)||0,theta:Number($('#theta').value)}}
function resolve(s,angle=s.theta){const a=angle*Math.PI/180,n=[Math.cos(a),Math.sin(a),0],m=[-n[1],n[0],0],t=[s.xx*n[0]+s.xy*n[1],s.xy*n[0]+s.yy*n[1],0],sn=t[0]*n[0]+t[1]*n[1],tau=t[0]*m[0]+t[1]*m[1];return {n,m,t,sn,tau,mag:Math.hypot(...t)}}
const line=(x1,y1,x2,y2,col='#dce5ef',dash='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${col}" ${dash?'stroke-dasharray="'+dash+'"':''}/>`;
const txt=(x,y,s,anchor='middle')=>`<text x="${x}" y="${y}" text-anchor="${anchor}">${s}</text>`;
function plots(s,v){const c=(s.xx+s.yy)/2,r=Math.hypot((s.xx-s.yy)/2,s.xy),span=Math.max(r*1.25,10),k=85/span,X=a=>240+(a-c)*k,Y=a=>110-a*k;let h='';for(let i=-2;i<=2;i++){const a=c+i*span/2;h+=line(X(a),20,X(a),195)+txt(X(a),210,a.toFixed(0));const b=i*span/2;h+=line(145,Y(b),335,Y(b))+txt(134,Y(b)+3,b.toFixed(0),'end');}h+=line(140,Y(0),345,Y(0),'#9db0c5')+`<circle cx="240" cy="110" r="${r*k}" fill="none" stroke="#487eaf" stroke-width="2"/>`+line(240,110,X(v.sn),Y(v.tau),'#d19442')+`<circle cx="${X(v.sn)}" cy="${Y(v.tau)}" r="5" fill="#c47a24"/>`+txt(460,211,'σₙ →','end')+txt(15,17,'τ ↑','start')+txt(240,15,`In-plane principals: ${(c+r).toFixed(1)}, ${(c-r).toFixed(1)} MPa`);$('#mohr').innerHTML=h;
 const lim=Math.max(20,Math.abs(c)+r)*1.15,px=a=>45+a*410/180,py=a=>108-a*82/lim;h='';for(let a=0;a<=180;a+=45)h+=line(px(a),23,px(a),192)+txt(px(a),208,a+'°');for(let j=-2;j<=2;j++){let a=j*lim/2;h+=line(45,py(a),455,py(a))+txt(38,py(a)+3,a.toFixed(0),'end');}h+=line(45,py(0),455,py(0),'#9db0c5');for(const [key,col]of [['sn','#397bbc'],['tau','#ba771f']]){let d='';for(let a=0;a<=180;a++)d+=(a?'L':'M')+px(a)+','+py(resolve(s,a)[key]);h+=`<path d="${d}" fill="none" stroke="${col}" stroke-width="2"/>`+`<circle cx="${px(s.theta%180)}" cy="${py(v[key])}" r="4" fill="${col}"/>`;}h+=line(px(s.theta%180),23,px(s.theta%180),192,'#879db5','3 3')+txt(50,15,'MPa','start')+txt(450,15,'Blue σₙ · amber τ','end');$('#sweep').innerHTML=h;}
function update(){const s=read(),v=resolve(s);$('#theta-value').textContent=Number(s.theta.toFixed(1))+'°';for(const [id,key]of [['sn','sn'],['tau','tau'],['mag','mag']])$('#'+id).textContent=v[key].toFixed(1)+' MPa';$('#calc').textContent=`n = (${v.n[0].toFixed(3)}, ${v.n[1].toFixed(3)}, 0)\nt = (${v.t[0].toFixed(1)}, ${v.t[1].toFixed(1)}, 0) MPa`;$('#insight').textContent=Math.abs(v.tau)<1e-7?'No shear on this cut: traction is normal to the plane.':`Traction is oblique to the cut normal. Its shear magnitude is ${Math.abs(v.tau).toFixed(1)} MPa; its sign follows the chosen tangent m.`;plots(s,v);render(s,v);window.tractionState={...s,...v};}
function stop(){playing=false;$('#animate').textContent='Animate cut';$('#animate').setAttribute('aria-pressed','false')}
for(const id of ['theta','xx','yy','xy'])$('#'+id).addEventListener('input',()=>{stop();update()});$('#preset').addEventListener('change',()=>{presets[$('#preset').value].forEach((v,i)=>$('#'+['xx','yy','xy'][i]).value=v);stop();update()});$('#principal').onclick=()=>{const s=read();$('#theta').value=(Math.atan2(2*s.xy,s.xx-s.yy)*90/Math.PI+360)%360;stop();update()};$('#flip').onclick=()=>{$('#theta').value=(Number($('#theta').value)+180)%360;stop();update()};$('#reset').onclick=()=>resetView();
$('#animate').onclick=()=>{if(playing){stop();return;}playing=true;last=0;$('#animate').textContent='Pause';$('#animate').setAttribute('aria-pressed','true');function frame(time){if(!playing)return;if(last&&time-last>65&&!document.hidden){$('#theta').value=(Number($('#theta').value)+1)%360;update();last=time;}if(!last)last=time;requestAnimationFrame(frame)}requestAnimationFrame(frame)};update();
try{const T=await import('three'),{OrbitControls}=await import('./3pb-viewer/vendor/OrbitControls.js');const container=$('#scene'),renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));container.appendChild(renderer.domElement);const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,50);camera.up.set(0,0,1);const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.minDistance=3;controls.maxDistance=12;const paint=()=>renderer.render(scene,camera);resetView=()=>{camera.position.set(3.2,1.6,2.4);controls.target.set(0,0,0);controls.update();paint()};resetView();controls.addEventListener('change',paint);
const box=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(1.6,1.6,1.4)),new T.LineBasicMaterial({color:0x68819c,transparent:true,opacity:.6}));scene.add(box);const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(new Float32Array(18),3));const plane=new T.Mesh(geo,new T.MeshBasicMaterial({color:0x4e7ca8,transparent:true,opacity:.3,side:T.DoubleSide,depthWrite:false}));scene.add(plane);const borderGeo=new T.BufferGeometry().setFromPoints(Array.from({length:5},()=>new T.Vector3()));const border=new T.Line(borderGeo,new T.LineBasicMaterial({color:0x739aca}));scene.add(border);
const origin=new T.Vector3(),arrow=(color)=>{const a=new T.ArrowHelper(new T.Vector3(1,0,0),origin,1,color,.12,.065);scene.add(a);return a};const normal=arrow(0xe3eaf3),total=arrow(0xf78383),normalTraction=arrow(0x6eaefe),shear=arrow(0xf9c575);const dot=new T.Mesh(new T.SphereGeometry(.025,12,8),new T.MeshBasicMaterial({color:0xffffff}));scene.add(dot);
function label(text,pos){const c=document.createElement('canvas');c.width=64;c.height=64;const cx=c.getContext('2d');cx.font='32px Arial';cx.fillStyle='#c5d7ed';cx.textAlign='center';cx.fillText(text,32,42);const sprite=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(c),depthTest:false}));sprite.position.copy(pos);sprite.scale.set(.22,.22,1);scene.add(sprite)}for(const [text,v]of [['x',new T.Vector3(1.1,0,0)],['y',new T.Vector3(0,1.1,0)],['z',new T.Vector3(0,0,1.1)]]){const ax=new T.Line(new T.BufferGeometry().setFromPoints([origin,v]),new T.LineBasicMaterial({color:0x576f8d}));scene.add(ax);label(text,v)}
function setArrow(a,v,start=origin){const length=v.length();a.visible=length>1e-8;a.position.copy(start);if(a.visible){a.setDirection(v.clone().normalize());a.setLength(length,Math.min(.12,length*.3),Math.min(.065,length*.18))}}
render=(s,v)=>{const n=new T.Vector3(...v.n),m=new T.Vector3(...v.m),extent=.8/Math.max(Math.abs(m.x),Math.abs(m.y)),a=m.clone().multiplyScalar(extent),b=a.clone().negate();const pts=[new T.Vector3(a.x,a.y,-.7),new T.Vector3(b.x,b.y,-.7),new T.Vector3(b.x,b.y,.7),new T.Vector3(a.x,a.y,.7)];const p=geo.attributes.position;[0,1,2,0,2,3].forEach((k,i)=>p.setXYZ(i,...pts[k].toArray()));p.needsUpdate=true;geo.computeBoundingSphere();const bp=borderGeo.attributes.position;[0,1,2,3,0].forEach((k,i)=>bp.setXYZ(i,...pts[k].toArray()));bp.needsUpdate=true;borderGeo.computeBoundingSphere();const c=(s.xx+s.yy)/2,r=Math.hypot((s.xx-s.yy)/2,s.xy),scale=1.3/Math.max(100,Math.abs(c)+r),tn=n.clone().multiplyScalar(v.sn*scale);setArrow(normal,n.clone().multiplyScalar(.85),new T.Vector3(0,0,.5));setArrow(total,new T.Vector3(...v.t).multiplyScalar(scale));setArrow(normalTraction,tn);setArrow(shear,m.clone().multiplyScalar(v.tau*scale),tn);paint()};new ResizeObserver(()=>{const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();paint()}).observe(container);update();}catch(e){$('#error').hidden=false;console.error(e)}

if(window.parent!==window){const report=()=>window.parent.postMessage({type:'traction-explorer-height',height:Math.ceil(document.querySelector('main').getBoundingClientRect().height)},location.origin);new ResizeObserver(report).observe(document.querySelector('main'));report();}
