'use strict';
const $=id=>document.getElementById(id);
const ink='#20354d',blue='#245c85',orange='#c36733';
const line=(x1,y1,x2,y2,color,width=2,dash='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="${width}" ${dash?`stroke-dasharray="${dash}"`:''} stroke-linecap="round"/>`;
const label=(x,y,s,color=ink)=>`<text x="${x}" y="${y}" fill="${color}" font-family="system-ui,sans-serif" font-size="14">${s}</text>`;
const dot=(x,y)=>`<circle cx="${x}" cy="${y}" r="6" fill="white" stroke="${ink}" stroke-width="2"/>`;
function arrow(x1,y1,x2,y2,color){const dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy);if(len<.01)return '';const x=dx/len,y=dy/len;return line(x1,y1,x2,y2,color,2)+`<path d="M${x2} ${y2}L${x2-9*x+4*y} ${y2-9*y-4*x}L${x2-9*x-4*y} ${y2-9*y+4*x}Z" fill="${color}"/>`;}
function barResponse(degrees){const theta=degrees*Math.PI/180,c=Math.cos(theta),s=Math.sin(theta);return {c,s,extension:c,force:10*c,kxx:c*c,kxy:c*s,kyy:s*s};}
function trussResponse(h,load,area){const b=2,E=200e9,A=area*1e-6,L=Math.hypot(b,h);if(h===0)return {mechanism:true,L,k:0};const k=2*E*A*h*h/(L*L*L),uy=-load*1000/k,N=-load*1000*L/(2*h);return {mechanism:false,L,k,uy,N,reaction:load/2,strain:N/(E*A)};}
function updateBar(){const degrees=+$('angle').value,r=barResponse(degrees);$('angle-out').textContent=degrees+'°';$('bar-result').textContent=`Axial extension: ${r.extension.toFixed(3)} mm · N = ${r.force.toFixed(2)} kN (tension). Horizontal restoring stiffness: ${(10*r.kxx).toFixed(2)} kN/mm.`;$('matrix').textContent=`⎡ ${r.kxx.toFixed(3)}  ${r.kxy.toFixed(3)} ⎤\n⎣ ${r.kxy.toFixed(3)}  ${r.kyy.toFixed(3)} ⎦`;
const ax=125,ay=285,bx=ax+225*r.c,by=ay-225*r.s,dx=65,px=bx+dx*r.c*r.c,py=by-dx*r.c*r.s;
$('bar').innerHTML='<title>Axial projection of a horizontal displacement</title>'+line(80,310,525,310,'#dce3e8')+arrow(ax,ay,ax+60,ay,'#869aaa')+arrow(ax,ay,ax,ay-60,'#869aaa')+label(ax+67,ay+5,'x')+label(ax-16,ay-63,'y')+line(ax,ay,bx,by,blue,9)+line(bx+dx,by,px,py,'#a1b1bf',1,'4 4')+arrow(bx,by,bx+dx,by,orange)+arrow(bx,by,px,py,'#299487')+dot(ax,ay)+dot(bx,by)+label(ax-28,ay+25,'A · fixed')+label(bx-12,by-20,'B')+label(320,32,'δu = (1 mm, 0)',orange)+label(320,55,'δℓ = n · δu = cos θ mm','#299487')+label(320,78,'Arrows magnified for clarity')+label(140,330,`θ = ${degrees}° · L = 2 m`);
}
function updateTruss(){const h=+$('height').value,P=+$('load').value,A=+$('area').value,scale=+$('scale').value,r=trussResponse(h,P,A);$('height-out').textContent=h.toFixed(2)+' m';$('load-out').textContent=P+' kN';$('area-out').textContent=A+' mm²';$('scale-out').textContent=scale+'×';$('stiffness').textContent=(r.k/1e6).toFixed(2)+' kN/mm';$('force').textContent=r.mechanism?'Undefined':(r.N/1000).toFixed(2)+' kN';$('displacement').textContent=r.mechanism?'Undetermined':(r.uy*1000).toFixed(3)+' mm';$('reaction').textContent=r.mechanism?'Undetermined':r.reaction.toFixed(1)+' kN';
const large=!r.mechanism&&Math.abs(r.uy)/h>.05;let shift=r.mechanism?0:-r.uy*scale*75;const clipped=Math.abs(shift)>95;shift=Math.max(-95,Math.min(95,shift));
$('state').textContent=r.mechanism?(P===0?'Zero vertical stiffness: the linear system has no unique apex displacement.':'Zero vertical stiffness: no linear equilibrium exists for this vertical load.'):(large?'Large displacement relative to height: the linear prediction is outside a small-motion regime. ':'Linear elastic solution. ')+(clipped?'Drawing displacement capped to fit; numerical results are uncapped.':`Drawing magnified ${scale}×; readouts show actual values.`);
const y=285-h*75,yd=y+shift,color=r.mechanism||P===0?'#718697':r.N>0?'#287ca5':'#bd613c';
let svg='<title>Two-bar truss response</title>'+line(105,285,495,285,'#dce3e8',1,'4 5');
for(const x of [150,450]){svg+=line(x,285,300,y,'#a5b3bf',3,'6 6')+line(x,285,300,yd,color,7)+`<path d="M${x} 285l-14 23h28Z" fill="#e7edf2" stroke="${ink}"/>`+line(x-22,311,x+22,311,ink)+dot(x,285);}
svg+=dot(300,yd)+label(102,335,'A · fixed')+label(415,335,'B · fixed')+label(312,yd-8,'C');
if(P!==0)svg+=arrow(300,P>0?yd-60:yd+60,300,yd,P>0?orange:blue);svg+=label(325,Math.max(24,yd-48),`P = ${P} kN`)+label(22,28,r.mechanism?'Flat geometry · linear mechanism':`Each bar: ${(r.N/1000).toFixed(1)} kN`,color)+label(22,50,`h = ${h.toFixed(2)} m · base span = 4 m`);$('truss').innerHTML=svg;
const max=trussResponse(Math.sqrt(8),0,A).k/1e6*1.12,x=v=>60+v/3*505,z=v=>155-v/max*115;let points=[];for(let i=0;i<=120;i++){const hh=i/40;points.push(`${x(hh)},${z(trussResponse(hh,0,A).k/1e6)}`);}
$('curve').innerHTML='<title>Vertical stiffness versus apex height</title>'+label(60,22,'Vertical stiffness Kyy (kN/mm)')+line(60,40,60,155,'#9aaab8')+line(60,155,565,155,'#9aaab8')+`<polyline points="${points.join(' ')}" fill="none" stroke="${blue}" stroke-width="3"/>`+`<circle cx="${x(h)}" cy="${z(r.k/1e6)}" r="5" fill="${orange}"/>`+[0,1,2,3].map(v=>label(x(v)-4,177,String(v))).join('')+label(400,196,'Apex height h (m)')+label(7,48,max.toFixed(1))+label(30,158,'0');
}
for(const id of ['height','load','area','scale'])$(id).addEventListener('input',updateTruss);$('angle').addEventListener('input',updateBar);document.querySelectorAll('[data-angle]').forEach(b=>b.addEventListener('click',()=>{$('angle').value=b.dataset.angle;updateBar();}));$('shallow').addEventListener('click',()=>{$('height').value=.2;updateTruss();});$('flat').addEventListener('click',()=>{$('height').value=0;updateTruss();});$('reset').addEventListener('click',()=>{for(const [id,value]of Object.entries({height:1.5,load:20,area:400,scale:20,angle:35}))$(id).value=value;updateBar();updateTruss();});updateBar();updateTruss();
