import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const ROOT = new URL('./', import.meta.url);
const asset = p => new URL(p, ROOT).href;
const $=id=>document.getElementById(id), scene=new THREE.Scene();
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});}catch(e){$('error').hidden=false;$('error').textContent='WebGL is unavailable. Please open this viewer in a browser with hardware acceleration enabled.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));$('scene').appendChild(renderer.domElement);
const camera=new THREE.OrthographicCamera(-70,70,75,-75,.1,1500);camera.position.set(0,0,240);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.09;controls.enableRotate=true;controls.minZoom=.45;controls.maxZoom=12;controls.maxPolarAngle=Math.PI*.96;
const uniforms={blend:{value:0},amp:{value:12},surface:{value:0},reveal:{value:1}};
const material=new THREE.ShaderMaterial({side:THREE.DoubleSide,transparent:true,depthWrite:true,uniforms,vertexShader:`attribute vec2 uA; attribute vec2 uB; attribute float dA; attribute float dB; uniform float blend; uniform float amp; varying float damage; varying vec2 coord; void main(){vec2 u=mix(uA,uB,blend); damage=mix(dA,dB,blend); vec3 p=position+vec3(u*amp,0.);coord=position.xy;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`precision highp float;varying float damage;varying vec2 coord;uniform float surface;uniform float reveal;void main(){float d=clamp(damage,0.,1.);vec3 base=mix(vec3(.68,.79,.84),vec3(.87,.93,.94),clamp((coord.y+60.)/120.,0.,1.));vec3 c=mix(base,vec3(.96,.68,.30),smoothstep(.08,.55,d));c=mix(c,vec3(.80,.24,.13),smoothstep(.5,.86,d));c=mix(c,vec3(.14,.065,.085),smoothstep(.83,.98,d));if(surface>.5){c=mix(vec3(.10,.42,.51),vec3(.96,.72,.29),smoothstep(0.,.55,d));c=mix(c,vec3(.83,.15,.13),smoothstep(.55,1.,d));}float a=1.-reveal*smoothstep(.88,.995,d);if(a<.008)discard;gl_FragColor=vec4(c,a);}`});
let meta,geo,body,wire,time=1,playing=false,loop=true,currentPair='',displayTime=1;const cache=new Map(),pending=new Map();let networkError=null;
const resize=()=>{const r=$('scene').getBoundingClientRect();renderer.setSize(r.width,r.height);const aspect=r.width/r.height;camera.left=-76*aspect;camera.right=76*aspect;camera.top=76;camera.bottom=-76;camera.updateProjectionMatrix();};new ResizeObserver(resize).observe($('scene'));
function setPlaying(value){playing=value;$('play').textContent=value?'Ⅱ':'▶';$('play').setAttribute('aria-label',value?'Pause animation':'Play animation');}
function reset(){controls.reset();camera.position.set(0,0,240);controls.target.set(0,0,0);camera.zoom=1;camera.updateProjectionMatrix();controls.update();}
$('reset').onclick=reset;$('play').onclick=()=>{if(time>=879)time=1;setPlaying(!playing);};$('loop').onclick=()=>{loop=!loop;$('loop').setAttribute('aria-pressed',String(loop));};$('time').oninput=e=>{time=Number(e.target.value);setPlaying(false);};$('amplify').oninput=e=>{uniforms.amp.value=Number(e.target.value);$('ampValue').textContent='×'+e.target.value;$('scaleNote').textContent=Number(e.target.value)===1?'True displacement scale':`Displacement amplified ×${e.target.value}`;};$('trueScale').onclick=()=>{$('amplify').value=1;$('amplify').dispatchEvent(new Event('input'));};$('style').onchange=e=>uniforms.surface.value=Number(e.target.value);$('mesh').onchange=e=>{if(wire)wire.visible=e.target.checked;};$('openCrack').onchange=e=>uniforms.reveal.value=e.target.checked?1:0;
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','BUTTON'].includes(document.activeElement.tagName)){e.preventDefault();$('play').click();}});
async function binary(path){const r=await fetch(path);if(!r.ok)throw Error(`Could not load ${path} (${r.status}).`);return new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();}
async function frame(i){if(cache.has(i))return cache.get(i);if(pending.has(i))return pending.get(i);const promise=(async()=>{const b=await binary(asset(meta.frames[i].file)),n=meta.nodes,s=new Float32Array(b,0,2),q=new Int16Array(b,8,n*2),u=new Float32Array(n*2),d=new Float32Array(n),dq=new Uint16Array(b,8+n*4,n);for(let j=0;j<n;j++){u[2*j]=q[2*j]*s[0]/32767;u[2*j+1]=q[2*j+1]*s[1]/32767;d[j]=dq[j]/65535;}const f={u,d};cache.set(i,f);return f;})();pending.set(i,promise);try{return await promise;}finally{pending.delete(i);}}
function request(i){if(i<0||i>=meta.frames.length)return;frame(i).catch(e=>{networkError=e;setPlaying(false);$('error').hidden=false;$('error').textContent=e.message+' Reload the page to retry.';});}
function pair(t){let lo=0,hi=meta.frames.length-1;while(lo+1<hi){const mid=(lo+hi)>>1;if(meta.frames[mid].step<=t)lo=mid;else hi=mid;}return[lo,hi,(t-meta.frames[lo].step)/(meta.frames[hi].step-meta.frames[lo].step)];}
function update(t){const[a,b,f]=pair(t);request(a);request(b);if(!cache.has(a)||!cache.has(b)){$('status').textContent='Buffering frames…';return false;}if(currentPair!==`${a}:${b}`){const A=cache.get(a),B=cache.get(b);for(const [name,values] of [['uA',A.u],['uB',B.u],['dA',A.d],['dB',B.d]]){geo.attributes[name].array.set(values);geo.attributes[name].needsUpdate=true;}currentPair=`${a}:${b}`;for(let i=b+1;i<=b+3;i++)request(i);for(const k of cache.keys())if(k<a-2||k>b+4)cache.delete(k);}
uniforms.blend.value=THREE.MathUtils.clamp(f,0,1);const A=meta.frames[a],B=meta.frames[b],lerp=(x,y)=>x+(y-x)*f;$('disp').textContent=lerp(A.displacement,B.displacement).toFixed(4);$('load').textContent=lerp(A.load,B.load).toFixed(1);$('step').textContent=Math.round(t);$('time').value=t;$('status').textContent=playing?'Playing · interpolated':'Paused · drag to explore';const marker=$('marker');if(marker){marker.setAttribute('cx',chartX(lerp(A.displacement,B.displacement)));marker.setAttribute('cy',chartY(lerp(A.load,B.load)));}displayTime=t;return true;}
let chartX,chartY;function chart(){const c=meta.curve,maxX=Math.max(...c.map(r=>r[1])),maxY=Math.max(...c.map(r=>r[2]));chartX=x=>15+x/maxX*230;chartY=y=>110-y/maxY*96;const path=c.map((r,i)=>`${i?'L':'M'}${chartX(r[1]).toFixed(2)},${chartY(r[2]).toFixed(2)}`).join(' ');$('chart').innerHTML=`<path d="M15 14V110H245 M15 62H245 M15 14H245" fill="none" stroke="#293a49" stroke-width="1"/><path d="${path}" fill="none" stroke="#ddb274" stroke-width="2"/><circle id="marker" r="4.5" fill="#ffe0ac" stroke="#121d28" stroke-width="2"/>`;}
async function init(){const r=await fetch(asset('data/manifest.json'));if(!r.ok)throw Error('Simulation manifest could not be loaded.');meta=await r.json();const b=await binary(asset('data/mesh.bin.gz')),h=new Uint32Array(b,0,2),xy=new Float32Array(b,8,h[0]*2),indices=new Uint32Array(b,8+h[0]*8,h[1]),pos=new Float32Array(h[0]*3);for(let i=0;i<h[0];i++){pos[3*i]=xy[2*i]-32.5;pos[3*i+1]=xy[2*i+1]-60;}geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));for(const name of ['uA','uB','dA','dB']){const size=name.startsWith('u')?2:1;geo.setAttribute(name,new THREE.BufferAttribute(new Float32Array(h[0]*size),size).setUsage(THREE.DynamicDrawUsage));}geo.setIndex(new THREE.BufferAttribute(indices,1));body=new THREE.Mesh(geo,material);body.frustumCulled=false;scene.add(body);const wm=material.clone();wm.uniforms=uniforms;wm.wireframe=true;wm.depthWrite=false;wm.fragmentShader='void main(){gl_FragColor=vec4(.08,.15,.21,.18);}';wire=new THREE.Mesh(geo,wm);wire.position.z=.012;wire.frustumCulled=false;wire.visible=false;scene.add(wire);chart();$('dataNote').textContent=`${meta.nodes.toLocaleString()} vertices · ${meta.triangles.toLocaleString()} triangles · ${meta.frames.length} retained frames / ${meta.sourceFrames} source frames`;
await Promise.all([frame(0),frame(1)]);update(1);setPlaying(!matchMedia('(prefers-reduced-motion: reduce)').matches);window.viewer={seek(t){if(!Number.isFinite(t)||t<1||t>879)throw Error('Step must be between 1 and 879');time=t;setPlaying(false);},getState(){return{step:displayTime,playing,cachedFrames:cache.size,triangles:meta.triangles,amplification:uniforms.amp.value};}};
const ctx=document.modelContext;if(ctx?.registerTool)try{await ctx.registerTool({name:'set_simulation_step',description:'Pause and display a simulation step, interpolating retained frames.',inputSchema:{type:'object',properties:{step:{type:'number',minimum:1,maximum:879}},required:['step'],additionalProperties:false},execute:async input=>{window.viewer.seek(input.step);const[a,b]=pair(input.step);await Promise.all([frame(a),frame(b)]);update(input.step);return window.viewer.getState();}});}catch(e){console.warn('Optional browser tool unavailable',e);}}
let last=performance.now();function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.06);last=now;if(meta&&geo&&!networkError){const ok=update(time);if(playing&&ok){time+=dt*878/38*Number($('speed').value);if(time>879){time=loop?1:879;if(!loop)setPlaying(false);}}}controls.update();renderer.render(scene,camera);}requestAnimationFrame(animate);init().catch(e=>{$('error').hidden=false;$('error').textContent=e.message;$('status').textContent='Unable to load';console.error(e);});
